---READ TABLE

USE Test1;
GO

SELECT * 
FROM Orders;
---Understanding sales performance
--- What is the total number of orders in the dataset?
SELECT COUNT (OrderID) AS Order_count
FROM orders;

--- What is the total revenue generated across all orders?
SELECT SUM(TotalPrice) AS Total_Revenue
FROM orders;

---What is the average order value?
SELECT AVG(Quantity)  AS Avg_Order
FROM orders;

---What is the total revenue and order count by payment method?
SELECT PaymentMethod, COUNT(OrderID) AS TotalOrder, SUM (TotalPrice) AS TotalRevenue
FROM orders
GROUP BY PaymentMethod;

--- What is the average revenue generated by Referral Source?
SELECT ReferralSource, ROUND(AVG(TotalPrice), 2) AS Avg_Revenue
FROM orders
GROUP BY ReferralSource;

--- Analyzing Customer behaviour
---Who are the top 10 customers by total amount spent?
SELECT TOP 10
CustomerID, SUM(TotalPrice) AS TotalSpent
FROM orders
GROUP BY CustomerID
ORDER BY TotalSpent DESC;

--- Which customers generated the highest total revenue?
SELECT CustomerID, SUM(TotalPrice) AS TotalRevenue
FROM orders
GROUP BY CustomerID;

--Which referral source brings in the most customers and revenue?
SELECT  ReferralSource, COUNT(DISTINCT CustomerID) AS UniqueCustomers, 
SUM (TotalPrice) AS TotalRevenue
FROM orders
GROUP BY ReferralSource
ORDER BY  TotalRevenue DESC;

--- PRODUCT PERFORMANCE
--- Q1: Which products generate the most total revenue?
SELECT Product, COUNT (OrderID) AS TimesOrdered,
SUM(TotalPrice) AS TotalRevenue
FROM orders
GROUP BY Product
ORDER BY TotalRevenue DESC;

---Q2: Which products sell the highest total quantity (volume), regardless of revenue?
SELECT Product, SUM(Quantity) AS TotalQty
FROM orders 
GROUP BY Product
ORDER BY TotalQty;

---MONTHLY/YEARLY TREND
--- -- Q1: What is total revenue by year?
SELECT 
    YEAR(Date) AS OrderYear,
    COUNT(OrderID) AS TotalOrders,
    SUM(TotalPrice) AS TotalRevenue
FROM orders
GROUP BY YEAR(Date)
ORDER BY OrderYear;

---- Q2: What is total revenue by month, across all years combined? (Seasonality check)
SELECT 
    MONTH(Date) AS OrderMonth,
    DATENAME(MONTH, Date) AS MonthName,
    COUNT(OrderID) AS TotalOrders,
    SUM(TotalPrice) AS TotalRevenue
FROM orders
GROUP BY MONTH(Date), DATENAME(MONTH, Date)
ORDER BY OrderMonth;

